package:
  name: rap-green
  version: v1.0

source:
  url: https://github.com/SalihaZ/rap-green/archive/v1.0.tar.gz
  sha256: 6fffe70e950123715b22b49564f49f05d3c0b6193c765b96776eaee8394aabae
  #patches :
    #- 0001-makefile-patch

build:
  number: 0
  noarch: generic

requirements:
    
  host:
    #- htslib
    - openjdk
  run:
    - openjdk

test:
  commands:
    #java -jar RapGreen.jar command args
    #javac rapgreen/*.java
    #java -jar bin/RapGreen.jar -g example_files/example_unreconciled_tree.nwk -s example_files/species_tree_example.nwk #-nhx rap-green/example_files/annotated_output_genetre.nwk
    java -jar bin/RapGreen.jar --help

about:
  home: https://github.com/SouthGreenPlatform/rap-green
  license: GPL
  summary: "Manipulate and annotate phylogenetic trees"
    
extra:
  maintainer: 
    - dufayard
  identifiers:
    - biotools: rap-green
  