package:
  name: rapgreen
  version: "1.0"

source:
  #url: https://github.com/SouthGreen/rap-green/archive/v{{version}}.tar.gz
  url: https://github.com/SouthGreenPlatform/rap-green/releases/tag/v1.0
  sha256: 69799f32bb1dca6fc5408ffbe37990458259b4c8093773d660e247c31c6e864f

build:
  number: 0
  noarch: generic

requirements:
    
  host:
    - openjdk
  run:
    - openjdk
    - python

test:
  commands:
    - rapgreen --help
    

about:
  home: https://github.com/SouthGreenPlatform/rap-green
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: "Manipulate and annotate phylogenetic trees"
  doc_url: http://southgreenplatform.github.io/rap-green/

extra:
  maintainers: 
    - dereeper
  identifiers:
    - biotools: rap-green