{% set name = "rapgreen" %}
{% set version = "1.0" %}
{% set sha256 = "6fffe70e950123715b22b49564f49f05d3c0b6193c765b96776eaee8394aabae" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/SouthGreenPlatform/rap-green/archive/refs/tags/v{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic

requirements:
    
  host:
    - openjdk
  run:
    - openjdk
    - python

test:
  commands:
    - rapgreen --help
    

about:
  home: https://github.com/SouthGreenPlatform/rap-green
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: "Manipulate and annotate phylogenetic trees"
  doc_url: http://southgreenplatform.github.io/rap-green/

extra:
  maintainers: 
    - dereeper
  identifiers:
    - biotools:rap-green
