{% set version = "1.0.0-beta" %}
{% set sha256="d0e3119b254fb4e2bbbb0f8b3987ad18576ac7ef6e974b35760dc60ad18b342a" %}

package:
  name: rap-green
  version: {{ version }}

ource:
  url: https://github.com/SalihaZ/rap-green/releases/tag/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  #patches :
    #- 0001-makefile-patch

build:
  number: 0

requirements:
  build:
    - numpy
    - make
    - {{ compiler{'c'})}}
  #host:
    #- htslib
    #- zlib
  run:
    - openjdk
    #- zlib
# test:
#   commands:
#     - rap-green --version
about:
  home: https://github.com/SouthGreenPlatform/rap-green
  license: GNU
  license_file: LICENSE
  summary: "Manipulate and annotate phylogenetic trees"
  maintainer: dufayard # Optional
  
  
extra:
  identifiers:
    - biotools: rap-green