package:
  name: rap-green
  version: v1.0

Source:
  url: https://github.com/SalihaZ/rap-green/archive/v1.0.tar.gz
  sha256: 6fffe70e950123715b22b49564f49f05d3c0b6193c765b96776eaee8394aabae
  #patches :
    #- 0001-makefile-patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler{'cxx'})}}
  #host:
    #- htslib
    - zlib
  run:
    - openjdk
    - python
    - zlib

test:
  commands:
    #java -jar RapGreen.jar command args
    java -jar RapGreen.jar -g example_unreconciled_tree.nwk -s species_tree_example.nwk -nhx annotated_output_genetre.nwk

about:
  home: https://github.com/SouthGreenPlatform/rap-green
  license: GNU
  license_file: LICENSE
  summary: "Manipulate and annotate phylogenetic trees"
    
extra:
  maintainer: 
    - dufayard
  identifiers:
    - biotools: rap-green
  